### PR TITLE
Propose fix some typos

### PR DESCRIPTION
**Pull request by jeis2497052**
OK to repair a few more typos?

### CODE REVIEW

**Comment by jkitchin** [comment]
Why all the whitespace changes? They don't look correct to me, e.g. many of them look like one space less, which would not be multiples of 4.

**Comment by jkitchin** [comment]
Thanks for reporting the typos. I have pushed fixes for them in two commits above. I did not merge the PR because there were a lot of white space changes that didn't make sense, and I didn't want to cherry pick the typos, it was easier to just fix them.

**Comment by jeis2497052** [comment]
sorry about the whitespace changes.  I am using emacs+scimax+emacs Wiki snippet for trailing white space.  I will try to debug what went wrong.

**Comment by jeis2497052** [comment]
I found out the current markdown mode will change space to tabs without:
https://www.emacswiki.org/emacs/NoTabs
(setq-default indent-tabs-mode nil)
Why would tabs be a choice for markdown ?  I thought most docs avoided tabs at all costs.

Sorry again for adding them.

**Pull request closed without merging**
